baseurl: /
title: Alex Recker's Journal
author: Alex Recker
url: https://www.alexrecker.com
theme: jekyll-recker
permalink: /:year-:month-:day:output_ext

markdown: kramdown

plugins:
  - jekyll-analytics
  - jekyll-feed

jekyll_analytics:
  GoogleAnalytics:
    id: UA-42540208-6

exclude:
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - README.org
  - Rakefile
  - bin
  - gem
  - lib
  - spec
  - vendor

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
