title: Alex Recker's Journal
author: Alex Recker
url: https://www.alexrecker.com

permalink: /:year-:month-:day:output_ext

markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - README.org
  - Rakefile
  - bin
  - lib
  - s3_website.yml
  - spec
  - vendor

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
