baseurl: ''
title: Alex Recker's Journal
author: Alex Recker
email: alex@reckerfamily.com
twitter_username: alex_recker
github_username: arecker
url: https://www.alexrecker.com
theme: jekyll-recker
permalink: /:year-:month-:day:output_ext

markdown: kramdown

plugins:
  - jekyll-analytics
  - jekyll-feed

jekyll_analytics:
  GoogleAnalytics:
    id: UA-42540208-6

exclude:
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - README.org
  - Rakefile
  - bin
  - lib
  - spec
  - vendor

recker:
  twitter:
    access_token_secret_cmd: pass twitter/reckerbot/access-token-secret
    access_token_cmd: pass twitter/reckerbot/access-token
    consumer_api_key_cmd: pass twitter/reckerbot/consumer-api-key
    consumer_api_secret_cmd: pass twitter/reckerbot/consumer-api-secret-key
  
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
