permalink: /:year-:month-:day:output_ext
url: https://www.alexrecker.com

plugins:
- blog
- jekyll-feed
- jekyll-sitemap
- jekyll-tidy

include:
- _pages
- assets
- audio
- favicon.ico
- images
- old

keep_files:
- docs
- coverage

exclude:
- .jekyll-cache
- .yardoc
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- blog.gemspec
- data
- netlify.toml
- pages
- pandoc
- spec
- src
- www

defaults:
-
  scope:
    path: ''
  values:
    layout: 'default'
