url: https://www.alexrecker.com

plugins:
- blog
- jekyll-feed
- jekyll-sitemap
- jekyll-tidy

include:
- _pages
- assets
- audio
- images
- old

keep_files:
- docs
- coverage

exclude:
- .jekyll-cache
- .yardoc
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- blog.gemspec
- spec
- src

defaults:
-
  scope:
    path: ''
  values:
    layout: 'default'
