permalink: /:year-:month-:day:output_ext

markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - s3_website.yml

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
