baseurl: ''
title: Dear Journal
description: Daily, public journal by Alex Recker
author: Alex Recker
email: alex@reckerfamily.com
twitter_username: '@alex_recker'
github_username: arecker
facebook_username: alex.recker.581
linkedin_username: alex-recker-a0316481
url: https://www.alexrecker.com
permalink: /:year-:month-:day:output_ext
timezone: 'America/Chicago'

markdown: kramdown
highlighter: rouge

plugins:
- jekyll-feed
- jekyll-recker

exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- Rakefile
- jekyll-recker.gemspec
- lib
- pkg
- spec

recker:
  analytics: UA-42540208-6
  graphs: assets/images/graphs/
  twitter:
    access_token_secret_cmd: pass twitter/reckerbot/access-token-secret
    access_token_cmd: pass twitter/reckerbot/access-token
    consumer_api_key_cmd: pass twitter/reckerbot/consumer-api-key
    consumer_api_secret_cmd: pass twitter/reckerbot/consumer-api-secret-key
  slack:
    reckerfamily:
      channel: '#blog'
      username: 'reckerbot'
      emoji: ':reckerbot:'
      webhook_cmd: pass slack/reckerfamily/webhook | tail -1
    redalenfamily:
      channel: '#blog'
      username: 'reckerbot'
      emoji: ':reckerbot:'
      webhook_cmd: pass slack/redalenfamily/webhook | tail -1

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
