plugins:
- jekyll-feed

include:
- _pages
- assets
- audio
- images
- old

exclude:
- blog.rb
- Gemfile
- Gemfile.lock
- LICENSE
- README.md

defaults:
-
  scope:
    path: ''
  values:
    layout: 'default'
