permalink: /:year-:month-:day:output_ext
url: https://www.alexrecker.com

plugins:
- blog
- jekyll-feed
- jekyll-sitemap
- jekyll-tidy

include:
- _pages
- assets
- audio
- favicon.ico
- images
- old

keep_files:
- docs
- coverage

exclude:
- .jekyll-cache
- .yardoc
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- blog.gemspec
- pandoc
- spec
- src
- www

recker:
  twitter:
    access_token_secret_cmd: pass twitter/reckerbot/access-token-secret
    access_token_cmd: pass twitter/reckerbot/access-token
    consumer_api_key_cmd: pass twitter/reckerbot/consumer-api-key
    consumer_api_secret_cmd: pass twitter/reckerbot/consumer-api-secret-key
  slack:
    reckerfamily:
      channel: '#blog'
      username: 'reckerbot'
      emoji: ':reckerbot:'
      webhook_cmd: pass slack/reckers/webhook | tail -1
    redalenfamily:
      channel: '#blog'
      username: 'reckerbot'
      emoji: ':reckerbot:'
      webhook_cmd: pass slack/redalenfamily/webhook | tail -1

defaults:
-
  scope:
    path: ''
  values:
    layout: 'default'
