permalink: /:year-:month-:day:output_ext
url: https://www.alexrecker.com

include:
- _pages

exclude:
- .jekyll-cache
- Gemfile
- Gemfile.lock
- LICENSE
- Makefile
- README.md
- netlify.toml
- scripts

defaults:
-
  scope:
    path: ''
  values:
    layout: 'default'
