url: https://www.alexrecker.com

plugins:
- blog
- jekyll-feed
- jekyll-sitemap
- jekyll-tidy

include:
- _pages
- assets
- audio
- images
- old

keep_files:
- docs
- coverage

exclude:
- .jekyll-cache
- .yardoc
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- blog.gemspec
- spec
- src

recker:
  swears:
  - ass
  - asshole
  - booger
  - crap
  - damn
  - fart
  - fuck
  - hell
  - jackass
  - piss
  - poop
  - shit

defaults:
-
  scope:
    path: ''
  values:
    layout: 'default'
