plugins:
- jekyll-feed

include:
- _pages
- assets
- audio
- images
- old

keep_files:
- docs

exclude:
- .jekyll-cache
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- spec

defaults:
-
  scope:
    path: ''
  values:
    layout: 'default'
