plugins:
- jekyll-feed
- blog

include:
- _pages
- assets
- audio
- images
- old

keep_files:
- docs

exclude:
- .jekyll-cache
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- blog.gemspec
- spec
- src

defaults:
-
  scope:
    path: ''
  values:
    layout: 'default'
