#+TITLE: Ikea

I apologize for the silence – dear readers. My life has been in boxes
lately. I have just ‘up and left to a one bedroom bachelor pad in
Rockford.

Now that I think of it, there weren’t many boxes involved. I kind of
just stuffed everything in the trunk of my car. But I wanted to avoid
the morbidity of saying my life has been in the trunk of a car – I can
afford to exaggerate.

All settled in now. And by that, I mean specifically that I have an
Internet connection. It was kind of an ordeal. For three days, I
writhed in data-less darkness, waiting for the hand of my new ISP to
feed me. It was a dark time, folks. For a second, I think I almost
bought a book.

But the IV line is back, and I can already feel the antibodies kicking
in. To celebrate my new screaming 5 Mb/s connection, I’ve decided to
put together a little IKEA Assembly Survival Guide. The majority of my
nights since the big move has been spent in instruction manuals, tiny
screws, and instruction sets published by what must be the Antichrist
himself. By the time my fifth piece of furniture came together (and I
had to nap from the lack of blood in my brain… that happens when I
scream for longer than a few minutes), I think I had the process
figured out.

* 1. Don’t try to get too much done at once

IKEA furniture is like alcohol – hard alcohol. Really, that’s still an
understatement. IKEA furniture should be treated like strong
medication. You should never expect to handle putting together more
than one or two in a sitting. If you try, you will only fail. Trying
to put together more than two pieces of IKEA furniture in a single
night may not land you in the ER (heck – it might… I’ve never tried
it), but it will ensure your failure.

This is because putting IKEA furniture together is not like most
activities. It does not get easier as you practice, like bike-riding,
bowling, or talking to girls. IKEA assembly is intended to confuse
you. It will train you, challenge you, then make you doubt everything
you’ve done, only to repeat all of the above until you are dead. Most
people have the fortitude for about five of these cycles, which is
usually covered in the assembly of three medium sized furniture
pieces. Go no further.

* 2. Avoid real tools

Opening the envelope-sized box that houses your new futon only to see
what looks like to be the inside of C3PO, you may be tempted to grab a
box of your trusty tools. I urge you to resist this. In doing this,
you are already making too many assumptions about the hell you are
about to wade through. By taking up your own tools, you have already
decided that the job ahead can be done in the easiest way
possible. And thus begins the building of your expectations, the
ridicule of your intuition, and the heart attack of doubt that washes
over you.

You need to step into this like Charlie into Wonka’s factory, only
with much less optimism. Be a tourist in freakville. Take up your
fetal allen wrench and ball-point pen hammer, and prepare yourself to
do something very perverse. The only way to stop the viscous cycle of
entrapment is to expect to be miserable. Think about it – what can
exploit your positive attitude if you’ve already murdered it?

* 3. Proofread the instructions

Most think that the typical IKEA instruction manual is meant to inform
you. This is a fatal mistake. Most people don’t realize the IKEA
instruction manual isn’t written from the deductive perspective of,
say, someone who has already assembled the item. We cannot treat the
instruction manual like a set of instructions. If we read into it with
our own contemporary interpretation, we will be left disappointing
with it’s fallibility.

If we are to gain anything from the included instruction manual, we
are to treat it like an allegory. The instruction manuals are written
in ancient poetry. None of the text or diagrams are meant to be taken
literally. Without an appreciation for the artful freedom of the
instruction manual, it is of no use to you.

That being said, I’d like to highlight that it is really of no use to
you - yet. Before you begin building your altar to the gods of chaos,
be sure to spend a few hours with the manual, liberally applying your
own corrections. The manual is likely a first draft, even a scrawl or
a first pitch. Building as you read is probably the worst mistake you
can make.

* 4. If you start to feel confident - don't

Lastly, resist the urge to feel confident. The second you think to
yourself ‘Ah yes – I am getting this now”, put down your tools and
stop. This is either (a) dehydration setting in or (b) an omen that
you are about to do something completely wrong. In either case, be
sure to step back, rehydrate – maybe apply more gauze to your bleeding
knuckles while you are up – but before you get your head back down in
the grain, make sure that none of this makes any sense to you. As long
as you have lost yourself while building, you can be sure that will
find yourself again when you are done.

* Conclusion

So there are my rules of safe IKEA assembly. If you have any IKEA
stories, I’d love to hear them in the comments. Until my next post,
I’ll be here in my new bachelor pad eating noodles.
