[Settings]
  ID = "6db0d11b-247f-43e4-b048-61a5168349a4"

[Build]
  Publish = "www"
  Functions = ""

[[Redirects]]
  From = "/our-new-sid-meiers-civilization-inspired-budget/"
  To = "https://archive.alexrecker.com/civ-budget.html"
  Status = 0
  Force = true

[[Redirects]]
  From = "/seinfeld.html"
  To = "https://archive.alexrecker.com/seinfeld.html"
  Status = 0
  Force = true

[[Redirects]]
  From = "/anxiety.html"
  To = "https://archive.alexrecker.com/anxiety.html"
  Status = 0
  Force = true

[[Redirects]]
  From = "/clockwork-orange.html"
  To = "https://archive.alexrecker.com/clockwork-orange.html"
  Status = 0
  Force = true

[[Redirects]]
  From = "/eyes-wide-shut.html"
  To = "https://archive.alexrecker.com/eyes-wide-shut.html"
  Status = 0
  Force = true

[[Redirects]]
  From = "/full-metal-jacket.html"
  To = "https://archive.alexrecker.com/full-metal-jacket.html"
  Status = 0
  Force = true

[[Redirects]]
  From = "/jane.html"
  To = "https://archive.alexrecker.com/jane.html"
  Status = 0
  Force = true

[[Redirects]]
  From = "/linux.html"
  To = "https://archive.alexrecker.com/linux.html"
  Status = 0
  Force = true

[[Redirects]]
  From = "/noah.html"
  To = "https://archive.alexrecker.com/noah.html"
  Status = 0
  Force = true

[[Redirects]]
  From = "/rockford.html"
  To = "https://archive.alexrecker.com/rockford.html"
  Status = 0
  Force = true

[[Redirects]]
  From = "/san-francisco.html"
  To = "https://archive.alexrecker.com/san-francisco.html"
  Status = 0
  Force = true

[[Redirects]]
  From = "/the-top-5-ways-that-my-corgi-has-taught-me-how-to-be-a-better-person.html"
  To = "https://archive.alexrecker.com/the-top-5-ways-that-my-corgi-has-taught-me-how-to-be-a-better-person.html"
  Status = 0
  Force = true

[[Redirects]]
  From = "/uhh-yeah-dude.html"
  To = "https://archive.alexrecker.com/uhh-yeah-dude.html"
  Status = 0
  Force = true

[[Redirects]]
  From = "/using-selenium-buy-bus-pass/"
  To = "https://archive.alexrecker.com/selenium-bus-pass.html"
  Status = 0
  Force = true
