#+TITLE: Reality
#+DATE: <2014-11-05 Wed>
#+SUBTITLE: My journal from high school.  This is no ordinary journal, however. Judging by the eccentric handwriting, this thing must be full of philosophical howitzers.

Well hello there, readership. It’s been a while. I had to take a
longer hiatus from opinion exposition because Kubrick week took a lot
out of me. We technically didn’t even finish it. We stopped at the
intermission of A Space Odyssey , and just started watching Gilmore
Girls instead. The lesson here is that you cannot do a Kubrick movie
marathon the same way you would do a Star Wars marathon. I feel like
if we did actually finish his filmography in a week, Marissa and I
would have had to start smoking heavily, speaking in British accents,
and criticising scotch.

* Netflix, the Impetus

Rockford doesn’t really have a vibrant night life, so like most nights
we were driven to another Netflix documentary.  /Mortified Nation/
featured regular Americans reading humorous excerpts from their
diaries.

It wasn’t the best documentary. You only need ten to twenty minutes to
glean as much as it has to offer. We stopped the movie half way
through and turned to our own diaries.

Marissa’s was adorable, but expected. She was smart, godly,
conscientious, and open to new ideas. There were a few laughable
musings and some misplaced contrition, but who doesn’t have some of
that in their own childhood?

Then I found my journal.

* Quiet Kid

My journal was forged in that perfect combination of angst, puberty,
and absolute arrogance. Many of you who interact with me regularly
probably don’t know that the whole ‘talking to people’ activity is a
relatively new angle I’ve been trying out. I spent a good several
years brooding silently in my head.

Quiet kids get a reputation for being really smart. The Bible even
says /Better to be a silent fool, but considered wise/. But the big
disadvantage to living inside your head day-in-and-day-out is that you
don’t have anyone there to hear some of these crazy ideas and say,
“Hey man, you are being a total jackass right now.”

If you ever had someone like that in your life, cherish them. Give
them a call right now and shower them in gratitude for never letting
your write something like my journal.

* My Great Journal’s Premise

When I got a journal, I wasn’t interested in recording things that I
did. Everyone’s routine was mundaine. I dreaded the words ‘How was
your day’, and would want to crawl out of my skin every time I heard
them. I was much too interesting for merely describing my daily
activities.

I wanted a place to scrawl out all my genius ideas about the
universe. Being a mere high schooler, I couldn’t boast a lot of
experience - but I, you know, played a lot of Assassin’s Creed.

I was determined to be absolutely uninterpretable, even down to the
handrwiting. I tuned my handwriting into a series of unintelligible
slashes and eccentric whips around the page. After all, I had no time
to make any of this readable . The hearts and minds of all these other
people around me were at stake. I had to get my ideas down so my
followers would have them forever.

That being said - are you ready to read my journal, dear reader?

#+BEGIN_QUOTE
Chapter 1: Lunacy

Nothingness is beginning to sound like tearing between my ears. What
is lunacy? Insanity... sanity... sane... REALITY? Maybe the reality is
that everyone is, to an extent, insane.

Proof:

There are some things mortal man will never know (e.g., the span of
the universe)

The things, although unknown, are yet facts

Facts are real, therefore, reality

Therefore, all men are not fully in touch with reality

QED: Everyone is insane.
#+END_QUOTE

How are you all doing? Probably throwing a Bible at the mirror, no
doubt. This is heavy stuff, and we are only in chapter one.

Oh, and that thing at the end was a proof - like the ones you make in
Geometry to prove something is real. Because I wasn’t just making
stuff up. These are proofs of things that are real. I usually made
these when I was ready to declare another law of the universe. And if
you had asked me what “QED” means, I would have done just about
anything but admit I didn’t actually know.

These ‘grand revelations’ were usually just me playing around with
words. They usually end with more of a well teeeeeechnically maybe
truth. All I was trying to say is that insanity is a scale, rather
than a yes or no question - something mental health professionals have
known for decades, amazingly, without ever consulting my writings.

In fact, I’ll borrow from the good poet /Anonymous/ who expresses the
idea much more succinctly.

#+BEGIN_QUOTE
Crazy people see ghosts. Sane people just ignore them.
#+END_QUOTE

I was ridiculous, but I'll bear through the cringe and intellectual
silliness for your sake. Good night, readership.
