#+TITLE: San Francisco
#+DATE: <2016-10-09 Sun>

* O'Hare Airport - 5:50 PM CST

  I departed this afternoon from Madison's only airport.  It was
  quaint, and just about everything the air travel experience should
  be.  Even the fellow that makes you remove your belt and shoes under
  threat of a baton beating was no more authoritative than they should
  be.

  When I arrived at the gate, we soon were shepherded to an airplane
  that was so small, it looked like it was cut out of a museum exhibit
  meant to teach kids about flight.  It was a proper metal cigar tube
  with wings.  But after buckling into my prime window seat, we were
  asked to leave.  The pilot called it a "VIP movement".  Apparently
  there was somebody traveling through O'Hare airport who was so
  important that all other planes needed to wait until he was done.
  The unenthused stewardist clarified that it was President Barack
  Obama.

  "Thanks Obama!" I whispered.  Nobody acknowledged my joke.  Perhaps
  it was too "on the nose".

  After milling around in the airport for another hour, we were told
  to board in the same fashion.  Pavement, stairs, window seat,
  seat belts, and finally lift off.

  The flight was comically quick.  We were only in the air for
  twenty-seven minutes.  I swear I've made the same drive in only two
  hours.  During the flight, we were assured that since the delay
  affected all flights in an out of Chicago, any connecting flights
  were likely still viable.  That was good news, but I figured I had
  better just treat it like it was still the same time printed on my
  ticket.

  O'Hare, in contrast to the Dane County regional airport, is a war
  zone.  People were practically stabbing each other for AC outlets.
  Parents shoving Mcdonalds cheeseburgers into their kids' mouths.
  Additionally, navigating this airport was considerably more
  complicated.  My target gate number looked like a foot note out of
  an obscure academic journal.  I followed it's promise through a
  churning sea of angry, weary people.

  To my horror, arriving at gate H-11-A I beheld the great iron
  walkway retracting.  Despite what I had been assured, my connecting
  flight hat not been delayed.  It was still taking off at 5:00 PM,
  and I had arrived at 5:10 PM.

  As I waddled over two the desk, relinquishing my Forever 21 blue
  polka dotted bag to the ground, a furious bald man stepped in line
  in front of me.  Veins swelled around his temples.  He had that "I'm
  about to make a scene" look about him.

  "We need to be on that plane!"  He yelled and pointed his big
  muscular arm at the attendant.

  "Sir, we closed the gate ten minutes ago.  The walkway has already
  been retracted.  That's not possible."

  "Well get us on another flight!" he hollared.  His laser-guided
  trimmed goatee seemed to bristle.  The attendant yammered at a
  keyboard.  I knew what the answer would be before she said it.

  "There are no more seats on that flight, sir."  The man clenched his
  fists.  His female companion, clad in glossy exercise clothes rolled
  up behind her.  She read his frustration and joined in the
  beratement.

  "I don't see how it's our fault that Obama delayed our flight!
  That's not fair."

  "Thanks, Obama" I whispered again.  They did not acknowledge my
  joke.  I pulled out my phone and stared at my lock-screen.

  "Look!  We're doctors!  We NEED to be in San Francisco tomorrow
  because we have patients to treat!  Are you guys going to treat our
  patients instead?"

  My thoughts drifted.  I imagined walking into a doctor's office
  being greeted by an American Airline's employee.  /Good morning.
  Your doctor's flight was delayed, so the airline sent me to check
  your prostate/.

  "Honey," yelled baldy.  "They don't give a RAT'S ASS about us."  The
  two stormed away.  I sauntered up to the counter after them.

  "Hi... I think I have the same problem as that angry guy."  The
  attendant smirked as I continued, handing her my ticket.  "I was
  supposed to be on that connecting flight."  She proceeded to work on
  the computer.

  Wanting to capitalize on our rapport, I added "...and I'm not a
  doctor, so feel free to take your time."  The woman started
  laughing.

  "Don't worry about it - you were put on the next flight out.  Your
  plane leaves in two hours."  My mouth dropped in amazement.  "And
  feel free to tell that angry guy that you got the last seat."

  Which brings me here - Dear Reader.  Hunched over a wobbly table for
  one charging my phone at a sticky power outlet that I /may or may
  not/ have stabbed somebody for.  And I can't help but feel lucky.
  Now if you'll excuse me, I need to get to gate =H-EE-V-31.2 ~ a. ~
  (iii)=.  Hopefully sometime tonight I'll be somewhere in San
  Francisco - unless Obama manages to screw that up to.  Thanks, Obama.
