#+TITLE: Sitcoms
#+DATE: <2018-11-12 Mon>
#+SUBTITLE: Being a devoted Seinfeld fan, the idea of making room in my heart for another pop sensation portrayal of regular people set in New York irked me.


Marissa and I just finished our march through all 10 seasons of
Friends. I committed to watching the show about six months ago. I was
hesitant at first. Being a devoted Seinfeld fan, the idea of making
room in my heart for another pop sensation portrayal of regular people
set in New York irked me. Ten seasons later, I am starting to assemble
my doubts, critiques, musings for people without any meaningful
hobbies to read (I kid – please don’t find any hobbies and continue
reading). Between Seinfeld and Friends – which sitcom is supreme?

* Seinfeld Remained Emotionally Sterile

One virtue that Seinfeld remained true to is that they never made you
care about a character for longer than twenty minutes. Dating
relationships among the gang rarely spanned longer than a short story
arc, and even the ones that did never demanded any intellectual
investment from the viewer.

Why is a bizarrely emotionally sterile universe a good thing? This
gave the show watchability. The reason why Seinfeld reruns are the
best kind of reruns is because the story doesn’t matter. There is no
important context beyond the episode. What is the result? There is no
important order to the seasons. Even the reoccurring characters can
stand on their own in each episode. You don’t need to backtrack to
understand Elaine’s boyfriend Putty is a numskull who barely redeems
the relationship with raw physical attraction. There is no briefing
required to understand that George’s fiance Susan is smarter than he
is and pushes George into commitments that he is not mature enough
for. It only takes a few seconds to learn everything you need to know
about a character – whether it is their first appearance of fiftieth.

You can watch them in any order. There is no more tension in the
middle of the season than there is in the end of the season. You are
never required to take anything with you between episodes.

I felt Friends was weakest in this area. I would enjoy myself in the
middle of seasons, but by the last few episodes of the season, there
was too much contrived television tension to enjoy what was going on.

My favorite bit of irony in this fault was watching Joey ham it up in
a laughable soap opera performance, then put on a similar performance
in the show’s actual plot under the expectation that we are now
supposed to take them all seriously.

I would imagine this comes from pressure on the writers. They just
wanted to keep people interested in-between seasons. Consequently,
they resorted to kitchy cliffhangers and sacrificed the emotional
sterility championed by Seinfeld.

I would like to bring you to the pinnacle of Seinfeld’s strength. In
the end of season 7, George’s fiance Susan suffers a bizarre death
during wedding preparation. As the gang watches a stoic doctor give
George the grave news, the show reaches a crossroad. The sitcom stared
directly into the face of an emotional commitment. What do they do?
Watch (sorry about the quality… I think this might be a bootleg of a
bootleg).

#+BEGIN_HTML
<iframe width="420" height="315"
src="https://www.youtube.com/embed/xBAJjmN7JWE" frameborder="0"
allowfullscreen></iframe>
#+END_HTML

Exactly. They all just go out for coffee – and not because they want
to help George get over it – but because they are all bored . Staring
in the face of their first emotional story arc, the writer’s of
Seinfeld bravely nod, turn on their heels, and go back down the
mountain. Season 8 begins just like all the others with no trace of
emotional scarring. Not even a death interrupted their rhythm.

* The Finale of Friends was Fantastic

By far the greatest strength of Friends was the show’s finale. My
greatest disappointment with Seinfeld was how in the last episode, too
many things happened. There was no time to reflect on what had just
happened over the last nine years. I have been saying for years – that
all I wanted from the show’s finale was a silly plot, a slow pan over
an empty apartment, and the ending credits. I’m confident that this
won’t give away any spoilers, but this is ultimately exactly what
Friends did with the last episode. I was jealous.

Honestly, the last episode of Seinfeld has been the most confusing
thing in my life for a while now. It’s almost as if it was written by
the people who submit jokes to Reader’s Digest.

Beyond the two biggest differences that jumped out at me, I have
determined that the two are comparable. Seinfeld is still unshaken as
the best sitcom in my little book, only because I have always been so
impressed with its adherence to the rule of no emotion. I would
further award the show Friends with being comparable. Saying you like
Friends more than Seinfeld is something I would now consider valid
English (as opposed to saying you prefer Family Guy).

But that’s just my opinion. If you have any special loyalty to one
show or the other, I would be curious to hear why.
