# frozen_string_literal: true

source 'https://rubygems.org'

gem 'html-proofer'
gem 'liquid'
gem 'rack'
gem 'redcarpet'
gem 'rspec'
gem 'simplecov'
gem 'thin'

group :development do
  gem 'bump'
  gem 'liquid_debug'
  gem 'pry'
  gem 'rubocop'
end
