# frozen_string_literal: true

source 'https://rubygems.org'

gem 'fastimage'
gem 'html-proofer'
gem 'liquid'
gem 'mini_magick'
gem 'rack'
gem 'redcarpet'
gem 'rspec'
gem 'simplecov'
gem 'thin'
gem 'yard'

group :development do
  gem 'bump'
  gem 'liquid_debug'
  gem 'pry'
  gem 'rubocop'
  gem 'ruby-prof'
end
