#!/usr/bin/env python
"""Renders each file in data/ into an HTML file in www/"""

import argparse
import datetime
import pathlib

from lib import Page, load_json

parser = argparse.ArgumentParser()
parser.add_argument('--data', required=True, help='path to data directory')
parser.add_argument('--www', required=True, help='path to www directory')


def make_page(path):
    with path.open('r') as f:
        return Page(**load_json(f.read()))


def main(args):
    data_dir = pathlib.Path(args.data)
    www_dir = pathlib.Path(args.www)

    for path in data_dir.glob('*.json'):

        # TODO: remove once old data files aren't needed
        if path.name in ['info.json', 'quotes.json', 'redirects.json']:
            continue
        page = make_page(path)


if __name__ == '__main__':
    args = parser.parse_args()
    main(args)
