# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='created',
            new_name='subscribed',
        ),
    ]
