#!/usr/bin/env ruby

# frozen_string_literal: true

require 'json'
require 'yaml'

def log(msg)
  puts "gendata: #{msg}"
end

def pages
  Dir.glob('./_pages/**/*.html')
end

def nav
  list = pages.map do |page|
    name = File.basename(page, '*.html')
    nav = YAML.load_file(page)['nav']
    [name, nav]
  end
  list.select(&:all?).sort_by(&:last).collect(&:first)
end

def main
  data = {
    nav: nav
  }

  data.each do |key, value|
    path = "./_data/#{key}.json"
    log "writing #{path}"
    File.open(path, 'w') do |f|
      f.write JSON.pretty_generate(value)
    end
  end
end

main if __FILE__ == $0
