#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'yaml'

data = {
  git: {
    head: `git rev-parse HEAD`.strip,
    short_head: `git rev-parse --short HEAD`.strip,
    summary: `git log -1 --pretty=format:\"%s\" HEAD`.strip,
    count: `git rev-list --count master`.strip
  }
}

puts data.to_json
