#!/usr/bin/env ruby
# frozen_string_literal: true

require 'date'
require 'json'
require 'yaml'

def latest_file
  Dir['_posts/*.md'].max
end

# Latest journal entry
class Latest
  attr_reader :path, :data

  def initialize(path)
    @path = path
    @data = YAML.load_file path
  end

  def filename
    "#{File.basename(path).split('-entry.md').first}.html"
  end

  def filtered_data
    data.merge(
      {
        'description' => data['title'],
        'title' =>  Date.strptime(filename, '%Y-%M-%d.html').strftime('%A, %B %-d %Y')
      }
    )
  end

  def to_dict
    {
      filename: filename
    }.merge(filtered_data)
  end
end

data = {
  latest: Latest.new(latest_file).to_dict
}

puts data.to_json
