#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'yaml'

# A parsed markdown page.
class Page
  attr_reader :path, :data

  def initialize(path)
    @path = path
    @data = YAML.load_file(path)
  end

  def name
    File.basename path
  end

  def nav?
    data.key? 'nav'
  end

  def weight
    data['nav']
  end
end

def pages
  Dir['_pages/*.html'].map { |f| Page.new f }
end

data = {
  nav: pages.select(&:nav?).sort_by(&:weight).collect(&:name)
}

puts data.to_json
