#!/usr/bin/env bash

if [[ "$(uname)" == "Darwin" ]]; then SED="gsed"; else SED="sed"; fi

pages() {
    grep -o '^nav: \d$' _pages/* | \
        "$SED" 's/_pages\/\(.*\):nav: \([0-9]\+\)/\2 \1/' | \
        sort | awk '{ printf "\"%s\", ", $2 }' | \
        "$SED" 's/, $//g'

}

echo "[$(pages)]"
