#!/usr/bin/env ruby
# frozen_string_literal: true

require 'yaml'

def pages
  page_dir = File.expand_path(File.join(__dir__, '../_pages'))
  Dir["#{page_dir}/*.html"]
end

def pages_with_data
  pages.map { |p| [File.basename(p), YAML.load_file(p)['nav']] }
end

def nav
  pages_with_data.reject { |t| t.last.nil? }.sort_by { |t| t.last.to_i }.map(&:first)
end

puts nav.to_yaml
