#!/usr/bin/env ruby
# frozen_string_literal: true

require 'date'
require 'erb'
require 'time'
require 'yaml'

ATOM_LIMIT = 20

sitemap_template = ERB.new <<~XML
  <?xml version="1.0" encoding="UTF-8"?>
  <urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <% entries.each do |entry| %>
    <url>
      <loc>https://www.alexrecker.com<%= entry.pathname %></loc>
      <lastmod><%= entry.date.to_time.iso8601 %></lastmod>
    </url>
  <% end %>
  <% pages.each do |page| %>
    <url>
      <loc>https://www.alexrecker.com/<%= page %></loc>
    </url>
  <% end %>
  </urlset>
XML

atom_template = ERB.new <<~XML
  <?xml version="1.0" encoding="utf-8"?>
  <feed xmlns="http://www.w3.org/2005/Atom">
    <title>Dear Journal</title>
    <subtitle>Daily, public journal by Alex Recker</subtitle>
    <link href="https://www.alexrecker.com/feed.xml" rel="self" type="application/atom+xml" />
    <link href="https://www.alexrecker.com/" rel="alternate" type="text/html" />
    <updated><%= Time.now.iso8601 %></updated>
    <author>
      <name>Alex Recker</name>
      <email>alex@reckerfamily.com</email>
    </author>
    <id>https://www.alexrecker.com/feed.xml</id>
    <% entries.take(ATOM_LIMIT).each do |entry| %>
    <entry>
      <title><%= entry.title %></title>
      <link href="https://www.alexrecker.com<%= entry.pathname %>"/>
      <id>https://www.alexrecker.com<%= entry.pathname %></id>
      <published><%= entry.date.to_time.iso8601 %></published>
      <updated><%= entry.date.to_time.iso8601 %></updated>
      <summary><%= entry.description %></summary>
      <author>
        <name>Alex Recker</name>
        <email>alex@reckerfamily.com</email>
      </author>
      <% if entry.banner? %>
      <media:thumbnail xmlns:media="http://search.yahoo.com/mrss/" url="https://www.alexrecker.com/images/banners/<%= entry.banner %>"/>
      <media:content medium="image" url="https://www.alexrecker.com/images/banners/<%= entry.banner %>" xmlns:media="http://search.yahoo.com/mrss/" />
      <% end %>
    </entry>
    <% end %>
  </feed>
XML

def entry_files
  entry_dir = File.expand_path(File.join(__dir__, '../_posts'))
  Dir["#{entry_dir}/*.md"]
end

class Entry
  attr_reader :source

  def initialize(source)
    @source = source
  end

  def date
    slug = File.basename(source, '-entry.md')
    Date.strptime(slug, '%Y-%m-%d')
  end

  def title
    date.strftime('%A, %B %-d %Y')
  end

  def description
    frontmatter.fetch('title')
  end

  def frontmatter
    @frontmatter ||= YAML.load_file(source)
  end

  def pathname
    "/#{File.basename(source, '-entry.md')}.html"
  end

  def banner?
    frontmatter.key? 'banner'
  end

  def banner
    frontmatter.fetch('banner')
  end
end

def entries
  entry_files.sort.reverse.map { |f| Entry.new f }
end

def pages
  page_dir = File.expand_path(File.join(__dir__, '../_pages'))
  Dir["#{page_dir}/*.html"].map { |p| File.basename(p) }
end

case ARGV.first
when 'feed'
  puts atom_template.result(binding)
when 'sitemap'
  puts sitemap_template.result(binding)
else
  puts '$ genxml <feed|sitemap>'
  exit 1
end
