#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative '../src/lib'

pages = Blog.pages.select(&:nav?).sort_by { |p| p.frontmatter['nav'] }

links = pages.map { |p| "<a href=\"#{p.pathname}\">#{p.filename}</a>" }

elements = [
  '<br class="show-on-mobile" />',
  '<span class="float-right-on-desktop">'
] + links + ['</span>']

puts elements.join("\n")
