#!/usr/bin/env ruby
# frozen_string_literal: true

require 'yaml'

def base_template
  File.read 'pandoc/template.html'
end

def strip_frontmatter(contents)
  contents.sub(/---(.|\n)*---/, '')
end

source = "pages/#{File.basename(ARGV.first).sub('.html', '.md')}"
contents = File.read(source)
stripped_contents = strip_frontmatter(contents)
puts base_template.sub('$body$', stripped_contents)
