#!/usr/bin/env ruby

# frozen_string_literal: true

require 'rdoc'

require_relative '../newsrc/blog'

args = Blog::Arguments.parse(
  [
    [:from, 'path', nil, 'source file'],
    [:to, 'path', nil, 'target file']
  ]
)

Blog::Markup.render(from=args[:from], to=args[:to])
