#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative '../newsrc/blog'

args = Blog::Arguments.parse(
  [
    [:from, 'path', nil, 'source file'],
    [:to, 'path', nil, 'target file']
  ]
)

puts args
