#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../newsrc/blog'

SKIP_THESE = %w[
  data
  newsrc
  old
  scripts
  spec
  src
  www
].freeze

output = Blog::Files.directories.reject do |d|
  SKIP_THESE.include?(File.basename(d))
end.join(' ')

puts output
