#!/usr/bin/env -S ruby --disable=gems

# frozen_string_literal: true

require_relative '../src/lib'

EXCLUDE = [
  'gem',
  'partials',
  'scripts',
  'src',
  'www',
].freeze

puts Blog.directories.reject { |d| EXCLUDE.include?(d) }.join(' ')
