#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative '../src/blog'

EXCLUDE = [
  'gem',
  'scripts',
  'src',
  'www',
].freeze

puts Blog.directories.reject { |d| EXCLUDE.include?(d) }.join(' ')
