#!/usr/bin/env bash
set -e

log() {
    echo "strip-frontmatter: $@" 1>&2;
}

if [ -z "$1" ]; then
    cat <<EOF
strip-frontmatter: remove the frontmatter from a HTML/MD file.

Usage:
        $ strip-frontmatter path/to/file
EOF
    exit 1
fi

if ! test -f "$1"; then
    log "file \"$1\" not found!"
    exit 1
fi

cat "$1" | sed '1 { /^---/ { :a N; /\n---/! ba; d} }'
