#!/usr/bin/env -S ruby --disable=gems

# frozen_string_literal: true

base_dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))
test_dir = File.join(base_dir, 'src/tests')

require 'test/unit'
require_relative '../src/lib'

exit Test::Unit::AutoRunner.run(true, test_dir)
