# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('in_random', models.BooleanField(default=False, verbose_name='Include in random')),
                ('file', models.FileField(upload_to='documents')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('in_random', models.BooleanField(default=False, verbose_name='Include in random')),
                ('file', sorl.thumbnail.fields.ImageField(upload_to='images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
