# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortuneCookie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('in_random', models.BooleanField(default=False, verbose_name='Include in random')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
