#!/usr/bin/env ruby

# frozen_string_literal: true

require 'yaml'

require_relative 'lib/git'
require_relative 'lib/stats'

# Like File.join, except relative to the blog root.  Returns the blog
# root if called withour args.
def join(*args)
  rel = File.join(File.dirname(__FILE__), '..', *args)
  File.expand_path rel
end

# Logs a message for the user.
def log(msg)
  puts msg
end

# Returns the blog version string.
def version
  IO.read(join('VERSION')).chomp
end

# Returns a list of blog pages.
def pages
  Dir.glob(join('_pages/**/*.html'))
end

# Returns a list of journal entries..
def entries
  Dir.glob(join('_posts/*.md')).sort
end

# Returns a list of jorunal entriy dates.
def dates
  entries.map do |filename|
    slug = File.basename(filename, '-entry.md')
    Date.strptime(slug, '%Y-%m-%d')
  end
end

# Returns a sorted list of pages as they should appear in the site
# navigation.
def nav
  @nav ||= pages.map do |p|
    [File.basename(p, '*.html'), YAML.load_file(p)['nav']]
  end.select(&:all?).sort_by(&:last).collect(&:first)
end

# Runs the main blog routine.
def main
  log "Hi!  I'm blog (v#{version})."

  log 'Generating the site data.'
  File.open(join('_data/nav.yml'), 'w') { |f| f.write(nav.to_yaml) }
  File.open(join('_data/git.yml'), 'w') { |f| f.write(Git.context.to_yaml) }
  File.open(join('_data/stats.yml'), 'w') { |f| f.write(Stats.context.to_yaml) }
end

main if __FILE__ == $PROGRAM_NAME
