name: CI

on:
  push:
    branches:
    - ci

jobs:
  install:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'

  build:
    needs: install
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: make

  deploy:
    needs: build
    runs-on: ubuntu-18.04
    steps:
    - uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: './www'
      env:
        NETLIFY_AUTH_TOKEN: '${{ secrets.NETLIFY_AUTH_TOKEN }}'
        NETLIFY_SITE_ID: '${{ secrets.NETLIFY_SITE_ID }}'

  share:
    needs: deploy
    runs-on: ubuntu-18.04
    if: startsWith(github.ref, 'refs/tags/entry-')
    steps:
    - uses: actions/checkout@v2
    - run: echo "would share the post!"
