on:
  push:
    branches:
    - master
    paths:
    - '.github/**'
    - 'go.mod'
    - 'src/**'

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
